### ISSUE TITLE
How to change name server ip in DHCP scope ? 

### ISSUE THREAD

**Issue by xPakrikx** [BeryJu/gravity#682]
Hi

How can i change or use different name server ip for dhcp scope or use multiple ips. 
I tried this in DHCP options:
```
- tagName: router
  value: 10.78.0.1
- tagName: name_server
  value: 1.1.1.1
```

but looks like its ignored. Also is there a way to add other DHCP options like unifi controller etc. ? Or just these ? https://gravity.beryju.io/docs/dhcp/scopes/

thanks

**Comment by BeryJu** [comment]
For DNS, the intended behaviour is that if no option is set, gravity sets its own IP, but due to a bug (which the commit above fixes) the user-defined value wasn't overriding that correctly

For unifi, you can set `tag: 43` instead of `tagName` to set the DHCP option code directly, and instead of `value` you can set `value64` (which is an array) to any bytes that will be set as the option

For example

```yaml
- tag: 43
  value64:
    - Zm9v
```

**Comment by xPakrikx** [comment]
Thanks for help.

One more question. Can i configure more than one name server IP or this is not supported ?
